apiVersion: v1
kind: Secret
metadata:
  name: stack-auth-secrets
  namespace: stack-auth
type: Opaque
stringData:
  postgres-password: "password"
  stack-database-connection-string: "postgresql://postgres:password@postgres.stack-auth.svc.cluster.local:5432/stackframe"
  stack-database-replica-connection-string: "postgresql://postgres:password@postgres.stack-auth.svc.cluster.local:5432/stackframe"
  stack-server-secret: "BYVFNZ59iMXkhTTkl26JwIg7WZXMF2jjQ4CPPQjDjDc="
