apiVersion: v1
kind: Secret
metadata:
  name: stack-auth-secrets
  namespace: stack-auth
type: Opaque
stringData:
  postgres-password: "password"
  stack-server-secret: "BYVFNZ59iMXkhTTkl26JwIg7WZXMF2jjQ4CPPQjDjDc="
